### ISSUE TITLE
Paladin: Showing of value on action bar doesn't work

### ISSUE THREAD

**Issue by Veidimadr** [coolmodi/SpellCalc#10]
Hey Coolmodi, thank you for the nice addon. I got a trouble with showing of values on actions bar exceptionally for Paladin's spells (tested for different levels of pally, but the result always the same - numbers are not showing on action bar and I got a LUA errors). The counter in the error is never stopped. Could you check it? Thx in advance.
P.S. Tested with standard interface without any others addons + clear Cache & WTF.

Pally 1st lvl:
![image](https://user-images.githubusercontent.com/65803267/82723109-1d31ee00-9cd5-11ea-9a12-742163314b9d.png)

24lvl:
![image](https://user-images.githubusercontent.com/65803267/82723138-494d6f00-9cd5-11ea-832f-badf2405ed29.png)

full log:
![image](https://user-images.githubusercontent.com/65803267/82723103-0f7c6880-9cd5-11ea-9d19-3196d62cd64f.png)
![image](https://user-images.githubusercontent.com/65803267/82723329-e2c95080-9cd6-11ea-9971-4f2d9dd3fd66.png)
![image](https://user-images.githubusercontent.com/65803267/82723337-f1b00300-9cd6-11ea-8ee7-636f24e2fe25.png)
![image](https://user-images.githubusercontent.com/65803267/82723348-012f4c00-9cd7-11ea-87dd-787e4832e024.png)
![image](https://user-images.githubusercontent.com/65803267/82723364-15734900-9cd7-11ea-8658-e25270a65c57.png)
![image](https://user-images.githubusercontent.com/65803267/82723378-2459fb80-9cd7-11ea-92cb-b60a2b3d514b.png)
![image](https://user-images.githubusercontent.com/65803267/82723386-2cb23680-9cd7-11ea-82bd-7dd9c3f519a1.png)

**Comment by coolmodi** [comment]
Sorry about that, forgot to actually test this. Fixed in [0.7.1](https://github.com/coolmodi/SpellCalc/releases/tag/0.7.1) now.
