### ISSUE TITLE
 Interface\AddOns\SpellCalc\core/MeleeCalc.lua:244

### ISSUE THREAD

**Issue by Veidimadr** [coolmodi/SpellCalc#13]
Hi Coolmodi, I found one more error as druid, could you to check it pls?

LOG:

Message: Interface\AddOns\SpellCalc\core/MeleeCalc.lua:244: attempt to index field '?' (a nil value)
Time: Sun Jul  5 16:31:44 2020
Count: 2405
Stack: Interface\AddOns\SpellCalc\core/MeleeCalc.lua:244: attempt to index field '?' (a nil value)
Interface\AddOns\SpellCalc\core/MeleeCalc.lua:244: in function `GetMDPGB'
Interface\AddOns\SpellCalc\core/core.lua:306: in function <Interface\AddOns\SpellCalc\core/core.lua:151>
Interface\AddOns\SpellCalc\core/core.lua:569: in function `GetCalcedSpell'
Interface\AddOns\SpellCalc\UI/ActionbarValues.lua:116: in function <Interface\AddOns\SpellCalc\UI/ActionbarValues.lua:89>

Locals: self = <table> {
 levelDiff = 0
 isWhitehit = true
 isOffhand = false
 targetLevel = 21
 calcedSpell = <table> {
 }
 ldef = 105
 latk = 105
 isPvP = false
 ratk = 4
}
skillDiff = 101
hit = 74.800000
hitBonus = 0
weaponType = nil
(*temporary) = nil
(*temporary) = "mh"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 WEAPON_TYPE_TO_MASK = <table> {
 }
 CostHandler = <table> {
 }
 UpdateSpellPower = <function> defined @Interface\AddOns\SpellCalc\system/stats.lua:167
 target = <table> {
 }
 PrintDebug = <function> defined @Interface\AddOns\SpellCalc\helper.lua:85
 effectHandler = <table> {
 }
 BUFF_CONDITIONS = <table> {
 }
 targetBuffs = <table> {
 }
 UpdateAttackDmg = <function> defined @Interface\AddOns\SpellCalc\system/stats.lua:266
 itemSetData = <table> {
 }
 spellRankInfo = <table> {
 }
 JUDGEMENT_ID = 20271
 GetShapeshiftName = <function> defined @Interface\AddOns\SpellCalc\helper.lua:40
 FISHING_POLES = <table> {
 }
 UpdateAttackSpeeds = <function> defined @Interface\AddOns\SpellCalc\system/stats.lua:238
 IsOffHandWeaponEquipped = <function> defined @Interface\AddOns\SpellCalc\system/items.lua:285
 PrintSuccess = <function> defined @Interface\AddOns\SpellCalc\helper.lua:52
 WEAPON_TYPES_MASK = <table> {
 }
 TriggerUpdate = <function> defined @Interface\AddOns\SpellCalc\core/core.lua:535
 itemData = <table> {
 }
 GetCalcedSpell = <function> defined @Interface\AddOns\SpellCalc\core/core.lua:561
 SPELL_EFFECT_FLAGS = <table> {
 }
 FullUpdate = <function> defined @Interface\AddOns\SpellCalc\system/stats.lua:310
 SCHOOL_MASK = <table> {
 }
 RemoveTableEntry = <function> defined @Interface\AddOns\SpellCalc\helper.lua:9
 stats = <table> {
 }
 UpdateTalents = <function> defined @Interface\AddOns\SpellCalc\system/buffs.lua:437
 AddLocalization = <function> defined @Interface\AddOns\SpellCalc\i18n/loc.lua:13
 talentData = <table> {
 }
 IsMainHandWeaponEquipped = <function> defined @Interface\AddOns\SpellCalc\system/items.lua:280
 RemoveBuff = <function> defined @Interface\AddOns\SpellCalc\system/buffs.lua:298
 SPELL_AURA_TYPES = <table> {
 }
 PrintWarn = <function> defined @Interface\AddOns\SpellCalc\helper.lua:64
 SPELL_EFFECT_TYPES = <table> {
 }
 GetSettingsBuilder = <function> defined @Interface\AddOns\SpellCalc\libs/SettingsCreator.lua:553
 IsDualWieldEquipped = <function> defined @Interface\AddOns\SpellCalc\system/items.lua:297
 UpdateItems = <function> defined @Interface\AddOns\SpellCalc\system/items.lua:232
 UpdateTarget = <function> defined @Interface\AddOns\SpellCalc\system/target.lua:20
 GetCurrentSpellData = <function> defined @Interface\AddOns\SpellCalc\core/core.lua:578
 MeleeCalc = <table> {
 }
 EFFECT_TYPE = <table> {
 }
 debuffData = <table> {
 }
 buffData = <table> {
 }
 GetEffectiveManaPool = <function> defined @Interface\AddOns\SpellCalc\core/core.lua:122
 NewCalcedSpell = <function> defined @Interface\AddOns\SpellCalc\core/CalcedSpell.lua:194
 GetLocalization = <function> defined @Interface\AddOns\SpellCalc\i18n/loc.lua:29
 spellBaseInfo = <table> {
 }
 UpdateStats = <function> defined @Interface\AddOns\SpellCalc\system/stats.lua:217
 MagicCalc = <table> {
 }
 HEALING_CLASSES = <table> {
 }
 GetCurrentState = <function> defined @Interface\AddOns\SpellCalc\core/core.lua:583
 GetWeaponType = <function> defined @Interface\AddOns\SpellCalc\system/items.lua:303
 GetHandledSpellID = <fu

**Comment by coolmodi** [comment]
This error seems to be caused by the addon not correctly handling the equipped weapon type. 
Are you playing on an english client? What weapon(s) do you have equipped?

**Comment by Veidimadr** [comment]
I've got the error when equipped following items:
Battering Hammer - https://classic.wowhead.com/item=3198/battering-hammer 
Skinning Knife - https://classic.wowhead.com/item=7005/skinning-knife
Mining Pick - https://classic.wowhead.com/item=2901/mining-pick
The list can be incomplete, just tested only what I have in my bag.

It's not depended of client language, the same error in English client:
![image](https://user-images.githubusercontent.com/65803267/87030381-2fff7400-c1ea-11ea-8232-21ae9ca0bb92.png)

**Comment by coolmodi** [comment]
Oh, seems like I completely forgot the Miscellaneous weapon type. Attack is the only "spell" that even uses melee calculations as of now, and I never have that in my bars :D

**Comment by coolmodi** [comment]
Uploaded a fixed version just now.
