### ISSUE TITLE
SpellCalc Error

### ISSUE THREAD

**Issue by Kazo** [coolmodi/SpellCalc#16]
Sorry for not getting the full text, but I cant copy/paste the message since its spamming the error and wont let me copy it.
This is on a paladin if it matters.
https://i.imgur.com/1E8Su9D.png

**Comment by coolmodi** [comment]
What weapon do you have equipped while that happens? I thought I fixed all weapon types by now :/

**Comment by Kazo** [comment]
It does it with Sword/Off-Hand, Sword/Shield, and Two-Handers. I am a Paladin if it matters.

**Comment by coolmodi** [comment]
I may have found the reason. HoW is a ranged attack, but not only is the ranged def type not implemented, it also shouldn't even use ranged hit+crit. It's said it uses melee cirt+hit, but I really don't know, makes no sense at all going by the client data.

I'll look into fixing it somehow on the weekend.

**Comment by coolmodi** [comment]
Should be fixed in 0.7.5, see releases.
