### ISSUE TITLE
Idol of Health Not taken into account

### ISSUE THREAD

**Issue by CaleG** [coolmodi/SpellCalc#18]
Idol of health reduces HT cast time by 0.15s, seeing how this changes the numbers would be nice to see.

**Comment by coolmodi** [comment]
It should be taken into account, it probably just doesn't trigger an update itself right now because it doesn't change stats. I'll fix that, but for now changing anything else that triggers updates should make it work. Swapping any gear pieces around that have stats on them should do the trick.

**Comment by coolmodi** [comment]
0.7.6 has a dummy effect for it implemented. It should now update when the item is swapped.
