### ISSUE TITLE
nil value error from core.lua on flatMod assignment

### ISSUE THREAD

**Issue by dyej** [coolmodi/SpellCalc#2]
![image](https://user-images.githubusercontent.com/3760563/72571431-8e781500-388d-11ea-8afc-559652721f1f.png)

So not sure what info you need to help debug this, feel free to ask me for anything else. I'm getting this constantly repeating (many times a second) error from line 249 in `core.lua` about trying to index this flatMod field when it is nil. I've looked at the line in question but I don't really know lua so I'm not sure what the issue is. I installed the latest from master branch just now.

**Comment by dyej** [comment]
I think I see what the issue is, on line 248 where you do a nil check for `stats.flatMod` you actually wrote `stats.flatMods` I can submit a PR if you'd like

**Comment by coolmodi** [comment]
Thanks for the report, fixed it just now.
