### ISSUE TITLE
Moonkin issues

### ISSUE THREAD

**Issue by Isilrond** [coolmodi/SpellCalc#20]
shows no spelldamage in moonkin.
using TukUI and automatically changing actionbars

**Comment by coolmodi** [comment]
I tried it with bear and cat form, and it seems to work fine. Does it also not work with those or is it just moonkin?

**Comment by Isilrond** [comment]
ok also not working for cat and bear for me. only the spell on 1 shows a number from Spellcalc addon - but actually not a correct one - no form 304dam, moonin 109dam. need a list of my addons or screens?

**Comment by coolmodi** [comment]
Try disabling all other addons and toggle on error reporting (`/console scriptErrors 1`) and check if it works or if it throws errors.

With only TukUI (https://www.tukui.org/classic-addons.php?id=1) and this addon active it works for me.
