### ISSUE TITLE
ElvUI ActionBar support is wrong as of ElvUI v1.38

### ISSUE THREAD

**Issue by sarge101** [coolmodi/SpellCalc#21]
As per the title; As of ElvUI v1.38 they seem to have changed/fixed their actionbar ordering so that they are now in accordance with blizzard actionbar ordering. This means that currently the actionbar spellcalc text shown is assigned to the wrong actionbar. 

![image](https://user-images.githubusercontent.com/510189/103989293-6b9de980-51df-11eb-9d46-587c1d72b14e.png)

Fix is simple enough:
![image](https://user-images.githubusercontent.com/510189/103989869-4198f700-51e0-11eb-9b56-2f19d045725a.png)

**Comment by coolmodi** [comment]
Thanks for the info, uploaded an update.
