### ISSUE TITLE
Nil value Lua error on buttonText

### ISSUE THREAD

**Issue by alexchantastic** [coolmodi/SpellCalc#22]
Started getting the following Lua error after upgrading to 0.8.1:

```
ActionBarValues.lua:152: attempt to index upvalue 'buttonText' (a nil value)
```

This seems to happen when I loot. Not sure if I happen to be hovering over any spells at the same time.

**Comment by coolmodi** [comment]
You somehow didn't download 0.8.1 but instead more recent code that introduced that error, but it's fixed now. Only download the latest release from the release page https://github.com/coolmodi/SpellCalc/releases, e.g. "SpellCalc-0.8.2-0043-classic.zip" as of now.

**Comment by alexchantastic** [comment]
Ah, I think I downloaded https://github.com/coolmodi/SpellCalc/releases/tag/0.8.2 instead. Thanks! Really appreciate this addon.
