### ISSUE TITLE
TBC Compatibility?

### ISSUE THREAD

**Issue by dyej** [coolmodi/SpellCalc#25]
Hi, just want to say I love this addon and use your tooltip info to do math with my spells daily!

I was wondering if you plan to continue releasing updates through TBC launch to cover some of the new ways spells/spell power/stats/etc work?

Thanks!

**Comment by coolmodi** [comment]
Thanks to having beta it's already done in the tbc branch and should also work for the prepatch. I'll add a new release before the 18th.

**Comment by dyej** [comment]
Awesome. Thanks again.
