### ISSUE TITLE
Error on mouseover Serpent Sting (and more hunter spells)

### ISSUE THREAD

**Issue by c11epm** [coolmodi/SpellCalc#26]
![image](https://user-images.githubusercontent.com/7381434/119105552-b8ab8b00-ba1d-11eb-8a8b-027374ad122b.png)

Not sure if I can get the whole error message into text form somehow, if that is wanted. please point me in the right direction!

Regards,

**Comment by c11epm** [comment]
Btw, thanks for a fantastic addon, absolutely love it on my Priest!

**Comment by coolmodi** [comment]
Hunter isn't supported. But it seems like I accidentally added some spell definitions at some point and haven't logged onto a hunter since, so I never noticed. I'll remove them again so there's no error.

**Comment by coolmodi** [comment]
Now fixed in 0.11
