### ISSUE TITLE
Error spam with "spellRankInfo"

### ISSUE THREAD

**Issue by Kazo** [coolmodi/SpellCalc#27]
Getting spammed an error each frame on my paladin.
spellId listed in Locals seems to be Divine Intervention, which does not have a rank.

Full error message here: https://pastebin.com/6xUmyrCT

**Comment by coolmodi** [comment]
Now fixed in 0.11

**Comment by c11epm** [comment]
![image](https://user-images.githubusercontent.com/7381434/120711098-42983100-c4bf-11eb-8693-3b89a7d4bf22.png)

Additional similar bug when mouse over items in atlas loot this fires off. 
Maybe not spellcalc's fault?
Every item in atlas loot throws this on mouse over "start"

**Comment by coolmodi** [comment]
Uploaded a new version fixing the tooltip error spam.
