### ISSUE TITLE
Playing With Fire - Fire Mage Talent "Uses unknown effect 31, or invalid effect setup."

### ISSUE THREAD

**Issue by Torrontogosh** [coolmodi/SpellCalc#29]
Fire specced Mage, selected this talent today and got a message that asked me to report. The talent Playing with Fire increases spell damage caused by 1/2/3% and increases spell damage taken by 1/2/3%. All three steps threw the error message.

**Comment by coolmodi** [comment]
Thanks for reporting, it's fixed now.
