### ISSUE TITLE
ActionBar value problem with macros

### ISSUE THREAD

**Issue by omega** [coolmodi/SpellCalc#3]
I have some rank-less macros on my action-bars ( `/cast Mind Blast`), which results in highest rank being cast, but SpellCalc shows calculations for Rank 1. 

The calculation in the tooltip seems correct, so not sure if this is fixable? `GetMacroSpell` has two return values according to https://vanilla-wow.fandom.com/wiki/GetMacroSpell, but SpellCalc only uses the first one now, and I haven't checked if the second one is correct for rank-less macros..

Examples of macros that it ends up showing the wrong number for:

```
#showtooltip Mind Blast
/run UIErrorsFrame:Hide()
/console Sound_EnableErrorSpeech 0
/cast [harm,nodead] Inner Focus
/console Sound_EnableErrorSpeech 1
/run UIErrorsFrame:Clear() UIErrorsFrame:Show()
/cast [@mouseover,harm,nodead] [] Mind Blast
```

```
#showtooltip
/cast [@player] Power Word: Shield
```

**Comment by omega** [comment]
Ehh, for some reason, me going in and copy-pasting the macros and saving them again fixes this issue 🤷‍♂ , I'll close this issue now, sorry for the spam!

**Comment by coolmodi** [comment]
Just for the sake of clarification: GetMacroSpell actually returns the spell ID, not the spell name, which is why it works for any rank like it's used in the addon currently.
