### ISSUE TITLE
Priest: Consider T5 set bonus

### ISSUE THREAD

**Issue by whichwit** [coolmodi/SpellCalc#32]
2pc T5 returns 100 mana if Greater Heal heals target to full. Request to consider separate effective cost and HPM calculation from positive proc.

**Comment by coolmodi** [comment]
0.15 has support for that set bonus. If 2 pieces are equipped an additional "If healed to full" section should appear in the tooltip with additional efficiency information.

**Comment by whichwit** [comment]
Thank you!
