### ISSUE TITLE
Multiple "No effect handler for effect XXXX" errors in WotLK-Classic

### ISSUE THREAD

**Issue by clownburner** [coolmodi/SpellCalc#35]
Virtually any spell cast/mouseover generates a series of these errors. Something in the WotLK API must have changed. Happens on every class/spell I have been able to test. Are there any plans to update this for WotLK-classic?

**Comment by coolmodi** [comment]
Basically everything changed and the TBC version won't work. I got beta late and haven't put too much time into it. Pala, Druid, Priest and WL mostly work on the wotlk branch, but not without errors. No clue how long until it'll be ready.

**Comment by Phikita** [comment]
Thanks for working on this appreciate the effort.

**Comment by coolmodi** [comment]
I uploaded an update that should work now. It should not be considered complete though. See https://github.com/coolmodi/SpellCalc/releases
