### ISSUE TITLE
Warlock spellstone isn't considered

### ISSUE THREAD

**Issue by Anonomit** [coolmodi/SpellCalc#41]
It's a warlock weapon enchantment which increases periodic damage (corruption, drain life/soul, etc.) you deal by 1%.
Firestone probably isn't included either, but I haven't checked.

[Spellstone (top rank)](https://www.wowhead.com/wotlk/spell=55194/grand-spellstone)
[Firestone (top rank)](https://www.wowhead.com/wotlk/spell=55158/grand-firestone)

**Comment by coolmodi** [comment]
Yes, I simply forgot them :D
Will add them in the next release.

**Comment by coolmodi** [comment]
Added in version 0.19
