### ISSUE TITLE
Glyph of Quick Decay issue

### ISSUE THREAD

**Issue by Anonomit** [coolmodi/SpellCalc#42]
Haste isn't being factored into corruption correctly with [Glyph of Quick Decay](https://www.wowhead.com/wotlk/item=50077/glyph-of-quick-decay).

In the image below, you can see that corruption is anticipated to tick 6x, every 2.61s, for a duration of 13.58s. These numbers don't add up (6 * 2.61 = 15.66). Corruption duration is longer than the expected 13.58s, and 15.66s feels about right. Perhaps [Eradication](https://www.wowhead.com/wotlk/spell=47197/eradication) is accidentally being treated as a permanent effect? When it did proc, the prediction was even lower (and still incorrect).

![FhgJvN2Keo](https://user-images.githubusercontent.com/67178487/195771750-002b3f7f-2104-4ab4-b77c-e73c5511b0d3.png)

**Comment by coolmodi** [comment]
Haste is currently applied twice to the duration due to a copy&paste error. Will be fixed with the next release.
