### ISSUE TITLE
Master Shapeshifter lua error

### ISSUE THREAD

**Issue by Anonomit** [coolmodi/SpellCalc#43]
Master Shapeshifter [Rank 1](https://www.wowhead.com/wotlk/spell=48411/master-shapeshifter) [Rank 2](https://www.wowhead.com/wotlk/spell=48412/master-shapeshifter) has started causing frequent errors. The errors did *NOT* start when the talent was first learned, or the first time a shapeshift was used/cancelled. They started happening suddenly later on, with no apparent cause.

```
SpellCalc\system/unitAuras.lua:103: Removed Master Shapeshifter-1 with scriptValue without having cached value!
[string "=[C]"]: in function `error'
[string "@SpellCalc\system/unitAuras.lua"]:103: in function <SpellCalc\system/unitAuras.lua:91>
[string "@SpellCalc\system/unitAuras.lua"]:218: in function `UpdateAurasForUnit'
[string "@SpellCalc\system/unitAuras.lua"]:258: in function `?'
[string "@SpellCalc\events.lua"]:25: in function <SpellCalc\events.lua:21>

Locals:
(*temporary) = "Removed Master Shapeshifter-1 with scriptValue without having cached value!"
```

Additional context:
The shapeshift form when the error was captured was Tree of Life.
This took place inside a dungeon.
The errors appeared to start when the shapeshift was removed.

**Comment by coolmodi** [comment]
Fixed in version 0.19
