### ISSUE TITLE
DK :C

### ISSUE THREAD

**Issue by SegoItCh** [coolmodi/SpellCalc#46]
3x ...ceSpellCalc\UI/actionbar/ActionBarValues.lua:348: attempt to index field 'events' (a nil value)
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:348: in main chunk

Locals:
_addon = <table> {
 stats = <table> {
 }
 AddLocalization = <function> defined @SpellCalc\i18n/loc.lua:12
 levelDefaultArmor = <table> {
 }
 effectHandler = <table> {
 }
 aurasPlayer = <table> {
 }
 MeleeCalc = <table> {
 }
 npcResistances = <table> {
 }
 ActionBarValues = <table> {
 }
 enchantData = <table> {
 }
 NewCalcedSpell = <function> defined @SpellCalc\core/CalcedSpell.lua:235
 GetBaseMana = <function> defined @SpellCalc\data/basemana.lua:585
 SetupActionButtonText = <function> defined @SpellCalc\UI/actionbar/buttonText.lua:142
 GetHandledSpellID = <function> defined @SpellCalc\core/core.lua:918
 Target = <table> {
 }
 scripting = <table> {
 }
 SCTooltip = <table> {
 }
 TriggerUpdate = <function> defined @SpellCalc\core/core.lua:906
 setItemData = <table> {
 }
 GetCurrentState = <function> defined @SpellCalc\core/core.lua:958
 mechanicAuras = <table> {
 }
 aurasTarget = <table> {
 }
 GetCalcedSpell = <function> defined @SpellCalc\core/core.lua:936
 itemEffects = <table> {
 }
 GetCurrentSpellData = <function> defined @SpellCalc\core/core.lua:953
 MagicCalc = <table> {
 }
 CostHandler = <table> {
 }
 UpdateManaRegen = <function> defined @SpellCalc\system/stats.lua:317
 GetEffectiveManaPool = <function> defined @SpellCalc\core/core.lua:182
 GetLocalization = <function> defined @SpellCalc\i18n/loc.lua:20
 CONST = <table> {
 }
 UpdateAurasForUnit = <function> defined @SpellCalc\system/unitAuras.lua:183
 util = <table> {
 }
 itemSetData = <table> {
 }
}
ADDON_EFFECT_FLAGS = <table> {
 TRIGGERED_SPELL = 256
 DMG_SHIELD = 4
 STACKABLE_AURA = 512
 CHANNEL = 16
 MANA_RESTORE = 1024
 DURATION = 1
 AUTO_ATTACK = 64
 ABSORB = 8
 DUMMY_AURA = 128
 TRIGGER_SPELL_AURA = 32
 HEAL = 2
}
SEAL_OF_RIGHTEOUSNESS = "Seal of Righteousness"
SEAL_OF_COMMAND = "Seal of Command"
PRAYER_OF_MENDING = "Prayer of Mending"
EARTH_SHIELD = "Earth Shield"
SEAL_OF_VENGEANCE = "Seal of Vengeance"
SEAL_OF_CORRUPTION = "Seal of Corruption"
ActionBarValues = <table> {
 Clear = <function> defined @SpellCalc\UI/actionbar/ActionBarValues.lua:333
 UpdateStyle = <function> defined @SpellCalc\UI/actionbar/ActionBarValues.lua:340
}
spellsInBar = <table> {
}
needsUpdate = <table> {
}
slotMap = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table>

**Comment by coolmodi** [comment]
Deathknight is still not supported. As of 0.19 unsupported classes shouldn't cause errors with the addon active though.
