### ISSUE TITLE
Druid Travel Form error

### ISSUE THREAD

**Issue by SegoItCh** [coolmodi/SpellCalc#47]
10x SpellCalc\system/unitAuras.lua:103: Removed Master Shapeshifter-1 with scriptValue without having cached value!
[string "=[C]"]: in function `error'
[string "@SpellCalc\system/unitAuras.lua"]:103: in function <SpellCalc\system/unitAuras.lua:91>
[string "@SpellCalc\system/unitAuras.lua"]:218: in function `UpdateAurasForUnit'
[string "@SpellCalc\system/unitAuras.lua"]:258: in function `?'
[string "@SpellCalc\events.lua"]:25: in function <SpellCalc\events.lua:21>

Locals:
(*temporary) = "Removed Master Shapeshifter-1 with scriptValue without having cached value!"

**Comment by coolmodi** [comment]
Fixed in version 0.19
