### ISSUE TITLE
Healing tooltip value slightly below actual value

### ISSUE THREAD

**Issue by Squantchies** [coolmodi/SpellCalc#5]
Hey coolmodi I love this addon, but on my resto shaman the healing values are slightly below the actual number.  For instance my lesser healing wave shows a SpellCalc heal of 1120-1217 but my heals go as high as 1300.  I took the average of about 20 heals and got a 1244 average heal, 76 more than the average heal from SpellCalc.  I would guess the addon is not calculating the Purification talent which gives +10% to healing on the base spell.  This works out to be about +90 healing for Lesser Healing Wave rank 6.  If the talent is being calculated into the tooltip then I'm not sure what might be causing the difference.  My total healing is calculated correctly at +671, and   the spell damage numbers look accurate to me.

Thanks,

**Comment by coolmodi** [comment]
Sorry for the late reply, but you're right, shaman resto talents were set to the wrong tree (elemental), so points in Restorative Totems, Tidal Mastery and Purification currently don't work at all. Gonna push an update tomorrow I guess.

**Comment by coolmodi** [comment]
Done, new version should work correctly: 
https://github.com/coolmodi/SpellCalc/releases/tag/0.6.3
If there's still a problem let me know.

**Comment by Tobias-Kohl** [comment]
Thanks for your work! = ) I also use this on my shaman, will test this directly. This mod is really great!

**Comment by Squantchies** [comment]
Awesome! Thanks for the update, gonna try it out now :)
