### ISSUE TITLE
Lua error when accessing addon options

### ISSUE THREAD

**Issue by evermore12** [coolmodi/SpellCalc#52]
Great addon, however i want to turn off the predicted avg spell values on actionbars. Whenever i go into settings i just get this error though. Is there any other way to turn it off?

Update: I can access the menu now. Thankfully it was just as easy as removing the part where the error was.

Message: ...ce3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:649: attempt to call method 'SetMinResize' (a nil value)
Time: Tue Apr 11 20:57:38 2023
Count: 2
Stack: ...ce3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:649: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:649: in function `?'
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:108: in function <...AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua:97>
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1724: in function `FeedGroup'
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1932: in function `Open'
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1960: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1958>
[string "=[C]"]: ?
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:72: in function <...AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua:70>
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface/AddOns/SpellCalc/libs/Ace3/AceGUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/InterfaceOptionsFrame.lua"]:29: in function `InterfaceOptionsList_DisplayPanel'
[string "@Interface/FrameXML/InterfaceOptionsFrame.lua"]:47: in function `InterfaceOptionsListButton_OnClick'
[string "*InterfaceOptionsFrame.xml:12_OnClick"]:2: in function <[string "*InterfaceOptionsFrame.xml:12_OnClick"]:1>

Locals: <none>

**Comment by coolmodi** [comment]
Fixed in 0.21
