### ISSUE TITLE
Season of Discovery?

### ISSUE THREAD

**Issue by Frankensteak** [coolmodi/SpellCalc#55]
Not an issue, but curious if you plan to make SpellCalc for SoD?

**Comment by juntulis** [comment]
that would be nice. 
btw, classic one works but not on new runes.

**Comment by jamesharling** [comment]
Came here to comment the same as @juntulis - install this version for SoD https://github.com/coolmodi/SpellCalc/releases/tag/0.9.1

**Comment by GoMapur** [comment]
Hi, it would be really nice to support runes in SOD :)

**Comment by coolmodi** [comment]
The new release supports SoD.
