### ISSUE TITLE
Crusader Strike LUA Error

### ISSUE THREAD

**Issue by Frankensteak** [coolmodi/SpellCalc#56]
Steps to Reproduce:
1. Have Crusader Strike slotted on your gloves
2. Login
3. See Error

Stack Trace:
1860x SpellCalc/core/effecthandlers.lua:636: No dummy aura handler for effect 2 on spell Crusader Strike!
[string "=[C]"]: in function assert'
[string "@SpellCalc/core/effecthandlers.lua"]:636: in function ?'
[string "@SpellCalc/core/effecthandlers.lua"]:819: in function ?'
[string "@SpellCalc/core/core.lua"]:816: in function <SpellCalc/core/core.lua:232>
[string "@SpellCalc/core/core.lua"]:974: in function GetCalcedSpell'
[string "@SpellCalc/UI/actionbar/ActionBarValues.lua"]:127: in function <...ceSpellCalc/UI/actionbar/ActionBarValues.lua:112>

**Comment by coolmodi** [comment]
Fixed in 0.21
