### ISSUE TITLE
Starsurge not scaling with Spell Damage

### ISSUE THREAD

**Issue by Frankensteak** [coolmodi/SpellCalc#58]
Testing shows Starsurge has a 1.0 SP coefficient. SpellCalc currently does not scale the tooltip with SP.

**Comment by coolmodi** [comment]
It has coef at 1 in addon files too. Not sure if the base values are correct in the current release though. I'll look into it after the update for P2 works.

**Comment by coolmodi** [comment]
Ok, problem was downranking penalty wasn't disabled in classic, and Starsurge has a spell level of 1.
Will be working next update, but that's ready when it's ready :D

**Comment by coolmodi** [comment]
Fixed in 0.21
