### ISSUE TITLE
bad argument

### ISSUE THREAD

**Issue by bygnub** [coolmodi/SpellCalc#6]
Message: Interface\AddOns\SpellCalc\system/buffs.lua:418: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Thu Apr 16 11:48:45 2020
Count: 1
Stack: Interface\AddOns\SpellCalc\system/buffs.lua:418: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: ?
[C]: in function `ipairs'
Interface\AddOns\SpellCalc\system/buffs.lua:418: in function `UpdateTalents'
Interface\AddOns\SpellCalc\system/stats.lua:284: in function `FullUpdate'
Interface\AddOns\SpellCalc\events.lua:20: in function `?'
Interface\AddOns\SpellCalc\events.lua:109: in function <Interface\AddOns\SpellCalc\events.lua:108>

Locals:

**Comment by coolmodi** [comment]
Are you by any chance trying to use this as a warrior, rogue or hunter? If so, as stated in the readme:

> Warrior, Hunter and Rogue have no support at all.

I may add a check so the addon doesn't load when on those classes, because I probably won't get to finish the rewrite on the core system to finish melee support for some time.

**Comment by bygnub** [comment]
no, this is a paladin. i get that error when i first login, it works fine
otherwise.

**Comment by coolmodi** [comment]
Can't reproduce it with a lvl 22 paladin. Also can't see how it's even possible to happen tbh. Does it only happen with that char?

**Comment by bygnub** [comment]
yeah it;s on a level 1 pala

**Comment by coolmodi** [comment]
I found another error with level 1 paladins and fixed it, but I still can't reproduce the error you got. Maybe try [the newest version](https://github.com/coolmodi/SpellCalc/releases) and see if you still get it. Maybe the error message you got was just misleading.

**Comment by bygnub** [comment]
latest version looks good :)
