### ISSUE TITLE
Priest: Power Infusion calculated incorrectly

### ISSUE THREAD

**Issue by blastehh** [coolmodi/SpellCalc#8]
The power infusion multiplier seems to be calculated on the base healing rather than the final healing power, this gives a lower predicted heal value.

e.g
base healing = 702
zhc+bpb brings it up to 1300 total
healing amount should be : (heal spell value + (1300 x coeff)) * Power infusion * crit multiplier
Actual should be (2021 + (1300*.857)) * 1.2 * 1.5 = 5643
Current calculation gives a max value of ((2021*1.2) + (1300x.857)) * 1.5 = 5309

**Comment by coolmodi** [comment]
You're right, I reused the same effect for PI that I also used for talents like Spiritual Healing. Never noticed myself.

**Comment by coolmodi** [comment]
New version should work as expected.
