### ISSUE TITLE
Issue when mousing over talents on a mage

### ISSUE THREAD

**Issue by sadhukar** [coolmodi/SpellCalc#9]
Hi, I am a frost mage. When I mouse over pyroblast on the fire tree, I keep getting this error:

![image](https://user-images.githubusercontent.com/10431751/82266822-a0b0af80-9962-11ea-991f-5c3f6f456991.png)

**Comment by coolmodi** [comment]
Pyroblast (and Mind Flay) rank 1 is indeed missing from the spell data. Update coming soon™.

**Comment by coolmodi** [comment]
Fixed in new version.
